export const defaultData = [
	{
		id: 1,
		document_type: "DNI",
		documente_number: "76576469",
		name: "Jaime González",
		last_name: "Loayza",
		distrito: "Lima",
		provincia: "Lima",
		departamento: "Lima",
		country: "Perú",
		date_register: "2023-10-25T15:30:00Z",
	},
	{
		id: 2,
		document_type: "DNI",
		documente_number: "23456789",
		name: "Carlos González",
		last_name: "Loayza",
		distrito: "Arequipa",
		provincia: "Arequipa",
		departamento: "Arequipa",
		country: "Perú",
		date_register: "2023-10-25T15:30:00Z",
	},
	{
		id: 3,
		document_type: "RUC",
		documente_number: "12345670",
		name: "Laura Fernández",
		last_name: "Loayza",
		distrito: "Cusco",
		provincia: "Cusco",
		departamento: "Cusco",
		country: "Perú",
		date_register: "2023-10-25T16:30:00Z",
	},
	{
		id: 4,
		document_type: "PASAPORTE",
		documente_number: "AB123456",
		name: "John Smith",
		last_name: "Loayza",
		distrito: "Lima",
		provincia: "Lima",
		departamento: "Lima",
		country: "Estados Unidos",
		date_register: "2023-10-25T17:30:00Z",
	},
	{
		id: 5,
		document_type: "DNI",
		documente_number: "34567890",
		name: "Ana Pérez",
		last_name: "Loayza",
		distrito: "Trujillo",
		provincia: "La Libertad",
		departamento: "La Libertad",
		country: "Perú",
		date_register: "2023-10-25T18:30:00Z",
	},
	{
		id: 6,
		document_type: "RUC",
		documente_number: "23456701",
		name: "Pedro Ramirez",
		last_name: "Loayza",
		distrito: "Arequipa",
		provincia: "Arequipa",
		departamento: "Arequipa",
		country: "Perú",
		date_register: "2023-10-25T19:30:00Z",
	},
	{
		id: 7,
		document_type: "PASAPORTE",
		documente_number: "BC234567",
		name: "Emily Johnson",
		last_name: "Loayza",
		distrito: "Cusco",
		provincia: "Cusco",
		departamento: "Cusco",
		country: "Estados Unidos",
		date_register: "2023-10-25T20:30:00Z",
	},
	{
		id: 8,
		document_type: "DNI",
		documente_number: "45678901",
		name: "Luis Torres",
		last_name: "Loayza",
		distrito: "Trujillo",
		provincia: "La Libertad",
		departamento: "La Libertad",
		country: "Perú",
		date_register: "2023-10-25T21:30:00Z",
	},
	{
		id: 9,
		document_type: "RUC",
		documente_number: "34567012",
		name: "Sofia Martinez",
		last_name: "Loayza",
		distrito: "Lima",
		provincia: "Lima",
		departamento: "Lima",
		country: "Perú",
		date_register: "2023-10-25T22:30:00Z",
	},
	{
		id: 10,
		document_type: "PASAPORTE",
		documente_number: "CD345678",
		name: "David Brown",
		last_name: "Loayza",
		distrito: "Arequipa",
		provincia: "Arequipa",
		departamento: "Arequipa",
		country: "Estados Unidos",
		date_register: "2023-10-25T23:30:00Z",
	},
	{
		id: 11,
		document_type: "DNI",
		documente_number: "56789012",
		name: "Marta García",
		last_name: "Loayza",
		distrito: "Trujillo",
		provincia: "La Libertad",
		departamento: "La Libertad",
		country: "Perú",
		date_register: "2023-10-26T14:30:00Z",
	},
	{
		id: 12,
		document_type: "RUC",
		documente_number: "45670123",
		name: "Javier Lopez",
		last_name: "Loayza",
		distrito: "Cusco",
		provincia: "Cusco",
		departamento: "Cusco",
		country: "Perú",
		date_register: "2023-10-26T15:30:00Z",
	},
	{
		id: 13,
		document_type: "PASAPORTE",
		documente_number: "DE456789",
		name: "Sophia Taylor",
		last_name: "Loayza",
		distrito: "Lima",
		provincia: "Lima",
		departamento: "Lima",
		country: "Estados Unidos",
		date_register: "2023-10-26T16:30:00Z",
	},
	{
		id: 14,
		document_type: "DNI",
		documente_number: "67890123",
		name: "Diego Vargas",
		last_name: "Loayza",
		distrito: "Trujillo",
		provincia: "La Libertad",
		departamento: "La Libertad",
		country: "Perú",
		date_register: "2023-10-26T17:30:00Z",
	},
	{
		id: 15,
		document_type: "RUC",
		documente_number: "56701234",
		name: "Linda Smith",
		last_name: "Loayza",
		distrito: "Arequipa",
		provincia: "Arequipa",
		departamento: "Arequipa",
		country: "Perú",
		date_register: "2023-10-26T18:30:00Z",
	},
	{
		id: 16,
		document_type: "PASAPORTE",
		documente_number: "EF567890",
		name: "William Davis",
		last_name: "Loayza",
		distrito: "Cusco",
		provincia: "Cusco",
		departamento: "Cusco",
		country: "Estados Unidos",
		date_register: "2023-10-26T19:30:00Z",
	},
	{
		id: 17,
		document_type: "DNI",
		documente_number: "78901234",
		name: "Lucia Perez",
		last_name: "Loayza",
		distrito: "Trujillo",
		provincia: "La Libertad",
		departamento: "La Libertad",
		country: "Perú",
		date_register: "2023-10-26T20:30:00Z",
	},
	{
		id: 18,
		document_type: "RUC",
		documente_number: "67812345",
		name: "Daniel Johnson",
		last_name: "Loayza",
		distrito: "Lima",
		provincia: "Lima",
		departamento: "Lima",
		country: "Perú",
		date_register: "2023-10-26T21:30:00Z",
	},
	{
		id: 19,
		document_type: "PASAPORTE",
		documente_number: "FG789012",
		name: "Olivia Taylor",
		last_name: "Loayza",
		distrito: "Arequipa",
		provincia: "Arequipa",
		departamento: "Arequipa",
		country: "Estados Unidos",
		date_register: "2023-10-26T22:30:00Z",
	},
	{
		id: 20,
		document_type: "DNI",
		documente_number: "89012345",
		name: "Hector Martinez",
		last_name: "Loayza",
		distrito: "Trujillo",
		provincia: "La Libertad",
		departamento: "La Libertad",
		country: "Perú",
		date_register: "2023-10-26T23:30:00Z",
	},
];
